package bg.com.bo.bff.providers.dtos.responses;

import bg.com.bo.bff.application.dtos.response.DPFListResponse;

import java.util.Arrays;

public class DPFMWResponseFixture {
    public static DPFMWResponse withDefault() {
        return DPFMWResponse.builder()
                .data(Arrays.asList(DPFMWResponse.DPFManagerMWData.builder()
                                .accountDpf("7892112")
                                .numDpf("311042")
                                .personNumber("56412")
                                .numDpfBGA("BGA-201-311042-0-0")
                                .ordinal("0")
                                .numCertificate("0")
                                .codeCurrency("068")
                                .highDate("2023-04-28")
                                .term("360")
                                .expirationDate("2024-04-22")
                                .rate("3")
                                .capital("200000")
                                .interest("6000")
                                .total("206000")
                                .managementCod("I")
                                .payFormInterestCod(" ")
                                .currencyDescription("BOLIVIANOS")
                                .currencyAbbreviation("Bs")
                                .statusCod(" ")
                                .statusDescription("SIN BLOQUEO")
                                .paymentMethod("AL VENCIMIENTO")
                                .drivingAccountDpf("INDIVIDUAL")
                                .productCod("86997")
                                .productDescription("DPF DESMA. INSTITUCIONALES - VCTO - NOMINATIVO M/N")
                                .clientCod("205")
                                .clientName("INSTITUCION FINANCIERA")
                                .plazaCod("2")
                                .plazaDescription("LA PAZ")
                                .build(),
                        DPFMWResponse.DPFManagerMWData.builder()
                                .accountDpf("7892136")
                                .numDpf("311044")
                                .personNumber("56412")
                                .numDpfBGA("BGA-201-311044-0-0")
                                .ordinal("0")
                                .numCertificate("0")
                                .codeCurrency("068")
                                .highDate("2023-04-28")
                                .term("370")
                                .expirationDate("2024-05-02")
                                .rate("3")
                                .capital("200000")
                                .interest("6166.67")
                                .total("206166.67")
                                .managementCod("I")
                                .payFormInterestCod(" ")
                                .currencyDescription("BOLIVIANOS")
                                .currencyAbbreviation("Bs")
                                .statusCod(" ")
                                .statusDescription("SIN BLOQUEO")
                                .paymentMethod("AL VENCIMIENTO")
                                .drivingAccountDpf("INDIVIDUAL")
                                .productCod("86997")
                                .productDescription("DPF DESMA. INSTITUCIONALES - VCTO - NOMINATIVO M/N")
                                .clientCod("205")
                                .clientName("INSTITUCION FINANCIERA")
                                .plazaCod("2")
                                .plazaDescription("LA PAZ")
                                .build())
                )
                .build();
    }
}